### ISSUE TITLE
Error with S1C

### ISSUE THREAD

**Issue by gabglus** [TomerFi/home-assistant-custom-components#11]
Hi Tomer,

I have HASS 0.69.1 and broadlink 0.9.

I received this error:

File "/home/pi/homeassistant/custom_components/sensor/broadlink_s1c.py", line 98, in async_setup_platform
    for i, sensor in enumerate(raw_data["sensors"]):
TypeError: 'NoneType' object is not subscriptable

I would appreciate your help.
Thanks in advance,
Gabriel

**Comment by TomerFi** [comment]
sorry for the delayed response,
is this issue still relevant?
