### ISSUE TITLE
Wrong hour

### ISSUE THREAD

**Issue by eggsterino** [TomerFi/home-assistant-custom-components#19]
The schedule time in the Switcher android app is correct (what I set), while the schedule time in hassio is 3 hours before.  I've checked and the hassio timezone and the local time are correct.

**Comment by eggsterino** [comment]
I cannot test it due to issue #25.

**Comment by TomerFi** [comment]
Maybe try deleting the schedules from the switcher app and then create them from HA.

**Comment by eggsterino** [comment]
Solved. I have deleted them and recreated them from the switcher app and now it's okay.
Weird, I've done it before and it did not work...
