### ISSUE TITLE
Error when setting schedule start/end field

### ISSUE THREAD

**Issue by eggsterino** [TomerFi/home-assistant-custom-components#25]
Hi
Whenever I try to change the start/end text box of the create schedule box - I get a popup error message: "Failed to call service input_text/set_value".

**Comment by TomerFi** [comment]
Can you share you logs please?

**Comment by TomerFi** [comment]
@eggsterino 
Do you the component `input_text`?

**Comment by eggsterino** [comment]
Did you mean to ask if I USE or INSTALLED the input_text component? There's
a word missing there.

Anyway, I don't have an inpu_text section in my configuration.yaml and
apparently this component is not loaded (I have a clean install of Hass.io
in docker.

Is there a way to load it?

**Comment by TomerFi** [comment]
Exactly.

Note it your log the the `switcher_aio` component is calling the `input_text.set_value`.
This service doesn't exist if the `input_text` component isn't configured.
You can check if this is the case in the services tool in HA, I'm sure you won't be able to find the `input_text.set_value` service.

To try and fix it, add a *dummy* input_text entity, as instructed [here](https://www.home-assistant.io/components/input_text/) and restart HA, I believe this will add the required service and this error.

**Comment by eggsterino** [comment]
Thanks, indeed it solved the problem.
