### ISSUE TITLE
switcher_aio and Google Assistant

### ISSUE THREAD

**Issue by eggsterino** [TomerFi/home-assistant-custom-components#26]
Hi

I'm trying to connect switcher to Google Assistant via the official Google Assistant plugin, however it does not support the switcher_aio domain. Is it possible to expose the turn_on/turn_off commands to the standard switch domain?
See - https://www.home-assistant.io/components/google_assistant/#configuration

Thanks!

**Comment by TomerFi** [comment]
You can configure a [Template Switch](https://www.home-assistant.io/components/switch.template/) for controlling the switcher entities.

**Comment by eggsterino** [comment]
Thanks !
