### ISSUE TITLE
Can't discover ip when in different subnet

### ISSUE THREAD

**Issue by BuSHari** [TomerFi/home-assistant-custom-components#8]
Hi,

Thank you for that component, very useful!
My network is divided to multiple subnets, and my my devices (PC, NAS, HA...) and switcher are not on the same subnet.
So when i try to use that component and it tries ti discover my ip of the switcher it doesn't recognise it.

Any chance that you can add an option to provide the ip of the switcher?

i've opened an issue also at https://github.com/NightRang3r/Switcher-V2-Python/issues/1

**Comment by NightRang3r** [comment]
Sorry, Not possible, The auto extract and auto IP detection works as following:

The script creates a listener on port 20002 UDP and wait for broadcasts from the switcher device.

If you are not on the same subnet it means you are not on the same broadcast domain and you will not be able to receive the broadcasts from the switcher device

**Comment by BuSHari** [comment]
I know that it’s not possible to discover other devices when you are on a different subnet, I ask if there is any chance that you can add an option to insert an ip to the extract function.

**Comment by NightRang3r** [comment]
I’m not sure I understand what you mean 

But, If you want to use the script to extract the device details it is not possible because I get the device id value from the broadcast

**Comment by BuSHari** [comment]
For your extract script I understood that you need get all the info from the broadcast, so there is no way to extract that info from a different subnet.

For Tomer HA component I already have the device id and everything else, so i only need to insert the ip so I can use that component.

**Comment by NightRang3r** [comment]
@BuSHari Got it, It should be possible, But that's a question for @TomerFi

**Comment by BuSHari** [comment]
Yes, that question for @TomerFi 
I wanted to know if it is also possible to do it in your script...

**Comment by NightRang3r** [comment]
@BuSHari Sure, My script is standalone code you can configure the IP address in the script it self

**Comment by TomerFi** [comment]
@BuSHari 
You can try my previous switcher v2 component.
It does exactly what you need, It doesn't relay on broadcast messages and it access the device recursively for state updates.

It's a platform for for the `switch` component and it's called [`switcher_heater`](https://github.com/TomerFi/home-assistant-custom-components/tree/master/switcher_heater#switcher-v2-boiler-switch).

Please note, the accessing the device recursively in that manner sometimes makes the device timeout, in that case you'll see a socket timeout error, but don't worry and it will fix itself at the next state updates.

**Comment by BuSHari** [comment]
i've used that component, but i moved to the new one because of the input select and other things.

Right now, i've moved the HA client to the Switcher subnet so i'm able to use the new component, but it will be great if you can add that option to the new component.

also i'm having troubles to add that new component to the homekit service, and the old one it worked
